### PR TITLE
Casbah+Salat based implementation of Journal

### PR DESCRIPTION
**Pull request by jumutc**
- Support of snapshotting 
- Serialization of messages and snapshots to JSON format
- Out-of-the-box support of MongoDB queries to snapshots (one can extend SalatDAO)

### CODE REVIEW

**Comment by krasserm** [comment]
Hi @jumutc thanks for your interest in Eventsourced and your contribution. Before it can be considered for a merge, I'd like to have the following items resolved or discussed:
- A journal that is part of the Eventsourced distribution must support any event type. A limitation to `MongodbEvent` is too restrictive. This doesn't mean that your journal cannot work together with Eventsourced if your application only uses events of this type, but if it doesn't pass the existing `JournalSpec` and `ReplaySpec` in `eventsourced-journal-common`it cannot be included in the main project.
- Journals shouldn't hard-code any serialization format. All existing journals use [MessageSerialization](https://github.com/eligosource/eventsourced/blob/0.5.0/es-journal/es-journal-common/src/main/scala/org/eligosource/eventsourced/journal/common/serialization/MessageSerialization.scala#L185) that delegates to a custom [event serializer](https://github.com/eligosource/eventsourced#serialization) for event serialization. If you'd like to have JSON serialization of `Message` serialization (instead of the default protobuf serialization) you can override [this setting](https://github.com/eligosource/eventsourced/blob/0.5.0/es-journal/es-journal-common/src/main/resources/reference.conf#L4) in your application config.
- What do you think about re-using the existing mongodb journal(s) and configure it with custom JSON serializers to achieve your goals? I must admit that I'm not experienced with MongoDB and related drivers/libs but I'm sure @ddevore can help you with any questions/comments you have regarding that.

WDYT?

Cheers,
Martin

**Comment by jumutc** [comment]
Hi Martin,

Please find my answers and thoughts below:
- I can include backup solution (using protobuf serialization) for non `MongodbEvent` events if needed. I have taken original `JournalSpec` and `ReplaySpec` from your sources and modified them in order to work with `MongodbEvent` and `MongodbSnapshotState` traits. For instance current `MongodbCassbahJournal` doesn't have tests for `ReplaySpec` since it is not supporting snapshots.
- MongoDB journals currently hard-code protobuf serialization and that's a major disadvantage for my project (together with the missing support of snapshotting). Currently `akka.serialization.Serializer` trait deals only with `Array[Byte]` which is not the optimal choice for Casbah since it hides the structure of the object (event or snapshot) and makes it impossible to perform queries. I have found that Salat library might be a good choice for me. But it is quite coupled to the Casbah wrapper. The only way to use it properly is to apply Salat annotations. One can further simplify and leverage the development of db-related code by extending `SalatDAO` abstract class.
- I have stated some of the existing problems with serialization in the previous paragraph. To complete my point of view I would like to emphasize the importance of maintenance and migration of event and snapshot case classes which can be quite problematic with protobuf and any other serialization extending `akka.serialization.Serializer`.  

WDYT?

Cheers,
Vilen

**Comment by krasserm** [comment]
Hi Vilen,

thanks for making your motivations explicit. So your main requirements are storing JSON directly in MongoDB instead of byte arrays for query purposes and support for snapshotting. 

Regarding snapshotting, we are currently working on a [generic snapshotting solutions for all journals](https://github.com/eligosource/eventsourced/issues/108). This should be available soon.

Having JSON documents instead of byte arrays in MongoDB makes completely sense to me, not only for the Casbah-based journal but also for the Reactivemongo-based journal. For me, the main question is how can we support that for both journals in a re-usable way without introducing another special-purpose MongoDB journal (I'm mainly concerned about maintainability here). This probably requires an additional layer (in the journal implementation) that:
- converts any event object to/from a JSON document
- is able to deal with byte arrays in existing event logs for backwards-compatibility (e.g. by delegating to the existing serializers).

The event <-> JSON converter should be configurable by the application and be able to deal with **any** event type. Maybe @ddevore can say more to my proposal.

For snapshotting, the implementation should be able to deal with very large snapshots (in the order of GB). It is therefore essential, that the object can be streamed directly to a snapshot storage backend without creating another temporary in-memory representation, which would approximately double the allocated memory. To me it seems that a Salat-based solution is having this problem (in contrast to the [proposed solution](https://github.com/eligosource/eventsourced/issues/108)).

WDYT?

Cheers,
Martin

**Comment by jumutc** [comment]
Hi Martin,

With JSON converters there might be a lot of tricky cases and lots of them are resolved by Salat library. The custom converter might be a good choice but there might be problems with integration to Casbah and other MongoDB wrappers.   

I don't see any problems with using current snapshotting-related case classes and interfaces to achieve good scalability and efficient memory usage. In a pure functional setting one can use monads to stream or chuck in-memory model to the snapshot. In my approach I provide user with the possibility to process `List[MongodbSnapshotState]` and split its in-memory model. This code can be quickly re-engineered in order to stream the data and save it to MongoDB in chunks.  Maybe some generic solution is possible for MongoDB journals. Right now I would prefer to have an image of my snapshots in a query-enabled format!  WDYT?

P.S. Having snapshots in MongoDB format has other preferences, like "schema migration", maintenance (once you're updating your domain model and you want to have backward compatibility)!

Cheers,
Vilen

**Comment by ironfish** [comment]
Hi Vilen,

Thanks for your ideas and contribution. I apologize for not responding sooner but I’m tied up with a roll out of a large distributed modular app built on top of Evensouced using the ReactiveMongo Journal. We are now in QA - Yahoo!. In addition I’m upgrading the ReactiveMongo and Casbah Journals to the latest versions of those drivers and adding Snapshot support.

When I first set out to create the MongoJournals I considered using Salat (used it in the past and really like what Rose has done), and storing the data as JSON as opposed to Binary. In fact, I have a prototype of that effort somewhere on disk. 

The issue that one runs into is that Eventsourced needs the Message to be generic. As I’m sure your aware the “Event” type on Message is Any. The present’s significant problems for Json parser’s as the parser needs to know the type of event to marshal and unmarshal and the event is always implementation specific. So in order to get around this problem, I would have had to add some sort of type attribute to Message (String of full class name of the event), and then use scala reflections in conjunction with the Json parser for marshaling. While this would work, I wasn’t happy with the performance implications, especially as the application grows and we introduce clustering. Your approach using Salat and the MongodbEvent was something I had considered but wasn’t comfortable with modifying core from a philosophical point of view as all Journals from an interface perspective must work the same way. My goal was for the Mongo journals to have no impact on core journaling.

So in the end, I chose Binary and we are quite happy. Our application is blazingly fast thanks to Eventsoured and STM's ;-). In addition all our queries (which are few) on the write site are done against ref/stm and we have no issues. For more complex data reasoning (where we have many queries), we have implemented eventual consistency through Akka remoting to our read side database (Mongo also) which does store the data in Json format. Our application essentially is a CQRS command sourcing app.

**Comment by ironfish** [comment]
Hi Martin,

In regards to a common Journal for all Mongo drivers, I'm still of the mind to have separate Journal's for Casbah and ReactiveMongo. The drivers are significantly different and I'm not sure its worth the effort craft a common Journal. One is synchronous (Casbah) while the other is asynchronous (ReactiveMongo). One uses SWRS (Casbah) and the other AWRS (ReactiveMongo). I think it would make reasoning about the Journals more difficult and maintenance more tedious.

All that being said, I'm always open to new ideas and better ways of solving the problem.

WDYT?

Cheers,

Duncan

**Comment by krasserm** [comment]
Hi Duncan,

I never meant to have a common journal for all Mongo drivers and fully agree that this doesn't make sense. I meant that we shouldn't have another casbah-based journal (using salat) in addition to the existing casbah-based journal.

I even want to go further: shall we really continue to support the casbah-based journal? I'd like to avoid blocking IO wherever possible. I'd rather want to focus on extending the reactivemongo-based journal to allow applications to configure it with custom event <-> `BSONDocument`converters (if a conversion to binary is not acceptable).

WDYT?

**Comment by krasserm** [comment]
Hi Vilen

> With JSON converters there might be a lot of tricky cases and lots of them are resolved by Salat library. The custom converter might be a good choice but there might be problems with integration to Casbah and other MongoDB wrappers.

With JSON converter I mean a converter that generates any structure/representation that can be further processed by Casbah and/or Reactivemongo. It is only important that
- there's a reasonable default converter (provided by the journal) that can deal with **any** event type
- an application can define a custom converter if needed (to override defaults)

It is not an option to force an application to use special event (and snapshot) types when using a default converter. This also means that a journal with default configuration must pass the existing `JournalSpec` (which would also avoid creating special-purpose tests by copy-paste-modify - something that should be avoided anyway). If, on the other hand, an application wants to use special event types and provide a special-purpose converter for it (e.g. for efficiency reasons) then this is perfectly fine.

See also my [previous message](#issuecomment-19373438).

> I don't see any problems with using current snapshotting-related case classes and interfaces to achieve good scalability and efficient memory usage. In a pure functional setting one can use monads to stream or chuck in-memory model to the snapshot. In my approach I provide user with the possibility to process `List[MongodbSnapshotState]` and split its in-memory model. This code can be quickly re-engineered in order to stream the data and save it to MongoDB in chunks.  Maybe some generic solution is possible for MongoDB journals. Right now I would prefer to have an image of my snapshots in a query-enabled format!  WDYT?

Same here. Snapshotting should support a default case where applications can stream snapshots of any type to a backend store (in whatever binary format). Should an application want to have a more specific serialization format, it should be able to configure that with a custom serializer.

**Comment by ironfish** [comment]
Hi Martin,

Okay now I understand what you were saying. Yes I don't think it makes sense to have two Casbah implementations and agree with your notion about going further and not supporting Casbah because of the IO issue. If we can come up w/ a custom event, then I think it makes perfect sense to use BSON as its still binary and can be used for more than just mongo. My only concern that the BSON parser may still need to reflectively convert the event, but I'm not sure about that and will have to do some research.

**Comment by krasserm** [comment]
> My only concern that the BSON parser may still need to reflectively convert the event, but I'm not sure about that and will have to do some research.

We could delegate that to application-specific converters (used by the journal). They can either do a very specific `BSONDocument` to event object conversion (without using reflection) or a more generic conversion via reflection (not sure if there are existing libs for that). It depends on the application specifics (# of event types, performance, ...) which is the better solution. A default converter however would convert an event to a byte array (as currently hard-coded in the reactivemongo journal).

This would allow us to offer a generic reactivemongo journal that meets @jumutc 's requirements soon (provided he's writing a custom converter) and we could enhance the journal in the future by offering further general-purpose converters (using reflection or not) if needed.

WDYT?

**Comment by jumutc** [comment]
Hi Duncan and Martin,

Thank you for your useful observations. With my current project I try to keep things simple and not to spend too much time for splitting read/write databases etc. I have certain problems right now with serialization to binary because once you update your domain model or event case classes your replay process is broken. I understand all the worries w.r.t. maintainability of similar journals, duplicated code etc., but I have certain worries if there is a comparable library which could deliver Salat-like functionality (meaning good and reliable serialization of complex classes to JSON)!!! If you need my help in prototyping or coding this generic solution for serialization I'm ready to help! I'm really waiting for this code because we cannot progress further!

Cheers,
Vilen

**Comment by krasserm** [comment]
Hi Vilen

> ... With my current project I try to keep things simple and not to spend too much time for splitting read/write databases etc. I have certain problems right now with serialization to binary because once you update your domain model or event case classes your replay process is broken. 

Well, if you use protobuf, you have binary serialization with backwards compatibility (and awesome performance in addition). This is supported by all journals in combination with [custom serialization](https://github.com/eligosource/eventsourced#serialization). If this is your only requirement you should be fine with what is available now. 

Also think about whether you really need strong read consistency on the stored data. If not, you still can run a background job with MongoDB and convert the binary event data to whatever you like. I'm following exactly this approach with HBase running map-reduce jobs (which scales very well with large datasets).

> I understand all the worries w.r.t. maintainability of similar journals, duplicated code etc., but I have certain worries if there is a comparable library which could deliver Salat-like functionality (meaning good and reliable serialization of complex classes to JSON)!!! If you need my help in prototyping or coding this generic solution for serialization I'm ready to help! I'm really waiting for this code because we cannot progress further!

It is absolutely fine if you use the journal you implemented in your own application, if it fits your needs. The traits `SynchronousWriteReplaySupport` and `AsynchronousWriteReplaySupport` were created exactly for the purpose that others can implement their own journals. If your implementation follows the contract required by these support traits you can be confident that it will work together with Eventsourced. 

So I think it's a good idea that you start with your own journal implementation and consider a migration once your requirements are implemented by the existing journals. Any help from your side is highly appreciated. Please create a ticket with all the requirements you have for extending the existing MongoDB journals.

Thanks,
Martin

**Comment by jumutc** [comment]
Dear Martin,

Thank you for your comments. Somehow I missed one line of code in `MessageSerialization` which enables us to use our own `.proto` specifications for domain classes. Although Google protobuf library is very nice and outputs very fast compact representations I'm not really interested in saving space rather saving time (maintaining `.proto` files and generating with `protoc` new augmented classes). Another strategy might be to do migrations in mongoDB and to use Salat as a default serialization/deserialization routine. I'm more interested in the latter approach. 

P.S. I will think about possible tickets for MongoDB related journals, because JSON serialization is very crucial for this backend storage!

Cheers,
Vilen

**Comment by krasserm** [comment]
Will be covered in a generic way by follow-up tickets.

**Pull request closed without merging**
