### PR TITLE
Add fn to customize hbase cf

### PR DESCRIPTION
**Pull request by patelh**
This allows customizing the column family used for storing events.  E.g. setting block cache, in-memory, compression, block size, and etc.

### CODE REVIEW

**Comment by patelh** [comment]
> Why not a parameter of type HColumnDescriptor directly?

Since the column family is instantiated with the name used by the HBase journal, you'd want to keep that internal to eventsourced, if it was passed in, the user of the library may use a different name for the column family, potentially causing a "user error".  A much broader change could be to make a configuration object which can be passed in to CreateTable and the HBase journal which provides custom column family name but that might be overkill.

**Comment by krasserm** [comment]
@patelh sorry for the late reply, somehow missed the notification from github. Your answer makes sense to me. Thanks a lot for your contribution.

**Comment by krasserm** [comment]
Build is running and snapshots should be in the Maven repo in about 15 minutes.

**Comment by patelh** [comment]
Awesome, thanks!

**Pull request merged**
