### PR TITLE
Upgraded to Akka 2.1.0-RC1 and Scala 2.10.0-RC1.

### PR DESCRIPTION
**Pull request by odd**
- Added Receive as return type to all receive methods to avoid compilation error:
  `missing parameter type for expanded function
  The argument types of an anonymous function must be fully known. (SLS 8.5)
  Expected type was: scala.runtime.AbstractPartialFunction[Any,Unit] with Serializable
  abstract override def receive = {`
- Removed override modifier from pushBehavior, popBehavior and clearBehaviorStack since these methods do not override anything anymore (probably means that the behavior related functionality is now broken).
- Renamed ask method in DefaultChannelSpec to ask0 since it otherwise interfered with AskSupport

### CODE REVIEW

**Comment by krasserm** [comment]
Hi Odd,

thanks a lot for your contribution, highly appreciate it. I'll take a closer next week, especially the custom behavior stack (that you already mentioned) needs to be completely re-written with Akka 2.1 (probably using a decorator for the ActorContext instead of overriding Actor).

**Comment by krasserm** [comment]
Odd, how did you run the tests? Running `sbt test` on your pull request yields

```
[info] Run starting. Expected test count is: 0
[info] DiscoverySuite:
[info] Run completed in 103 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 0, ignored 0, pending 0
[info] All tests passed.
```

i.e. 0 test are executed. Will look into it soon ...

Furthermore, `BehaviorSpec` should fail (see also previous comment). I could verify that by running it from my IDE.

**Comment by krasserm** [comment]
Switching back to sbt 0.11.3 fixes that i.e. runs the tests with a failing `BehaviorSpec` and all others passing.

**Comment by odd** [comment]
Ok. I had a little bit of trouble with the SBT setup, and must have left the version at 0.12 instead of 0.11. Sorry.

Greetings
Odd

**Comment by krasserm** [comment]
No worries, I'll dig into it and will also backport the fix for the custom behavior stack to the Akka 2.0 based version. Thanks again for your contribution, it enables the next release to support both Akka 2.0 and 2.1. Keep them coming :)

**Comment by krasserm** [comment]
Regarding the added `Receive` type to every actor's `receive` method, I posted a related question to scala-user: 

https://groups.google.com/forum/?fromgroups=#!topic/scala-user/2pcH-ck46Qg

This looks like a Scala 2.10.0-RC1 type inference issue to me. I'd prefer not to force library users to type-annotate `receive` in their actors.

**Comment by krasserm** [comment]
The related ticket is at https://issues.scala-lang.org/browse/SI-6575 and the pull request at https://github.com/scala/scala/pull/1530. According to initial feedback (on the scala-user list), this seems to be straightforward to fix.

**Comment by krasserm** [comment]
Pushed to branch [wip-akka-2.1](https://github.com/eligosource/eventsourced/tree/wip-akka-2.1)

**Comment by krasserm** [comment]
The extended behevior change support implemented for the Akka-2.1 based version has also been [backported](https://github.com/eligosource/eventsourced/commit/9bebf19e8a3402116321f342c6c69cfb003b8fd9) to the Akka-2.0 based version. The user guide has been [updated](https://github.com/eligosource/eventsourced#behavior-changes) as well.

**Comment by krasserm** [comment]
First successful run on integration server: https://travis-ci.org/#!/eligosource/eventsourced/builds/2961697

**Comment by odd** [comment]
Great news!
//Odd

**Comment by krasserm** [comment]
Odd, I meanwhile upgraded to Akka 2.1-SNAPSHOT and Scala 2.10.0-SNAPSHOT (containing the bugfix) and pushed to [wip-akka-2.1](https://github.com/eligosource/eventsourced/tree/wip-akka-2.1) again. The upgrade is based on the latest master. I'm sorry to say that I couldn't maintain your commit in the history, too many conflicts trying to merge the original contribution (and following changes). Doing the upgrade manually again was much easier than resolving the conflicts.

**Comment by odd** [comment]
Sounds great. Hope you could make some use of it. 

Greetings
Odd

**Comment by krasserm** [comment]
Absolutely, it also helped me a lot to discover how Akka 2.1 breaks 
existing features in the eventsourced lib so that I could fix that 
before releasing 0.4.0. Thanks again for your contribution.

Cheers,
Martin

Am 05.11.12 20:35, schrieb Odd Möller:

> Sounds great. Hope you could make some use of it.
> 
> Greetings
> Odd
> 
> On 5 nov 2012, at 16:23, Martin Krasser notifications@github.com wrote:
> 
> > Odd, I meanwhile upgraded to Akka 2.1-SNAPSHOT and Scala 
> > 2.10.0-SNAPSHOT (containing the bugfix) and pushed to wip-akka-2.1 
> > again. The upgrade is based on the latest master. I'm sorry to say 
> > that I couldn't maintain your commit in the history, too many 
> > conflicts trying to merge the original contribution (and following 
> > changes).
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/eligosource/eventsourced/pull/21#issuecomment-10084384. 

## 

Martin Krasser

blog:    http://krasserm.blogspot.com
code:    http://github.com/krasserm
twitter: http://twitter.com/mrt1nz

**Comment by krasserm** [comment]
Master now based on Scala 2.10.0-RC2 and Akka 2.1.0-RC2

**Pull request closed without merging**
